[project]
name = "data-contracts"
version = "1.0.0"
description = "Data contract for ingestion"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["jsonschema"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"